apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $PROJECT_NAME
  name: devops-go-sample
  labels:
    app: devops-go-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-go-sample
  template:
    metadata:
      labels:
        app: devops-go-sample
    spec:
      containers:
      - name: go
        image: $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME
